### ISSUE TITLE
new winamp plugin

### ISSUE THREAD

**Issue by winamp-girl** [vgmrips/vgmplay-legacy#98]
Hi

Can you relese a new winamp plugin because the latest one is from 2018

**Comment by ValleyBell** [comment]
Current releases can be found here: https://vgmrips.net/forum/viewtopic.php?t=112

**Comment by ValleyBell** [comment]
> Last update: 2023-12-31 (v0.51.1)

That is definitely not very old. (Source code of the current version can be found at <https://github.com/ValleyBell/vgmplay-libvgm>)

**Comment by vampirefrog** [comment]
Where are you seeing this 2018 release? Post the URL please.

**Comment by vampirefrog** [comment]
I am assuming you mean this: https://github.com/vgmrips/vgmplay-legacy/releases

**Comment by ValleyBell** [comment]
Well... that **is** the latest version of the legacy branch.
The new version has a new codebase and is in another repository, so it won't make sense to put it up here.

**Comment by vampirefrog** [comment]
I think the issue is that there is no notification on the releases page that the repo has moved, perhaps you could add a link to the newer repo, maybe even with a large, very visible heading, by editing the description of the last release.

Something like:

# heckin repo has moved, bro, go [here](https://github.com/ValleyBell/vgmplay-libvgm/releases)
